version = 0.1

[dev.deploy.parameters]
stack_name = "knock-knock-dev"
resolve_s3 = true
resolve_image_repos = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
region = "us-east-1"
parameter_overrides = "Environment=dev"
tags = "Project=KnockKnock Environment=dev ManagedBy=SAM"
